name: Build and publish release packages
permissions:
  contents: write
on:
  release:
    types: [created]

jobs:
  build-linux-binaries:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
            docker: debian:buster
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.docker }}
    steps:
      - name: Install dependencies
        run: |
            apt-get update
            apt-get install -y gcc-multilib clang cmake curl jq
      - uses: taiki-e/install-action@v2
        with:
          tool: protoc@22.2
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build and publish
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: qdrant
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}

  # build-mac-binaries:
  #   strategy:
  #     matrix:
  #       include:
  #         - target: x86_64-apple-darwin
  #           os: macos-latest
  #         - target: aarch64-apple-darwin
  #           os: macos-latest
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Install dependencies
  #       run: |
  #           brew update
  #           brew install gcc llvm cmake protobuf-c
  #     - uses: actions/checkout@v3
  #     - name: Build and publish
  #       uses: taiki-e/upload-rust-binary-action@v1
  #       with:
  #         bin: qdrant
  #         target: ${{ matrix.target }}
  #         token: ${{ secrets.GITHUB_TOKEN }}

  # build-windows-binaries:
  #   strategy:
  #     matrix:
  #       include:
  #         - os: windows-latest
  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Install minimal stable
  #       uses: dtolnay/rust-toolchain@stable
  #     - uses: actions/checkout@v3
  #     - uses: Swatinem/rust-cache@v2
  #     - name: Install Protoc
  #       uses: arduino/setup-protoc@v1
  #       with:
  #         repo-token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build
  #       run: cargo build --release --locked

  #     - name: Build and publish
  #       uses: taiki-e/upload-rust-binary-action@v1
  #       with:
  #         bin: qdrant
  #         token: ${{ secrets.GITHUB_TOKEN }}
